2024-02-22 20:03:55,652 - CRITICAL - Error caused by Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
Traceback (most recent call last):
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\middlewares.py", line 30, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\app\ocr_bot\core\handlers.py", line 82, in img_to_text
    await split_and_send(message, text)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\utils.py", line 52, in split_and_send
    await message.answer(text)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
2024-02-22 20:04:47,721 - CRITICAL - Error caused by Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
Traceback (most recent call last):
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\middlewares.py", line 30, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\app\ocr_bot\core\handlers.py", line 82, in img_to_text
    await split_and_send(message, text)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\utils.py", line 52, in split_and_send
    await message.answer(text)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
2024-02-22 20:05:32,561 - CRITICAL - Error caused by Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
Traceback (most recent call last):
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\middlewares.py", line 30, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\app\ocr_bot\core\handlers.py", line 82, in img_to_text
    await split_and_send(message, text)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\utils.py", line 52, in split_and_send
    await message.answer(text)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
2024-02-22 20:06:27,142 - CRITICAL - Error caused by Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
Traceback (most recent call last):
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\middlewares.py", line 30, in __call__
    return await handler(event, data)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "F:\OCR_telegram_bot\app\ocr_bot\core\handlers.py", line 82, in img_to_text
    await split_and_send(message, text)
  File "F:\OCR_telegram_bot\app\ocr_bot\core\utils.py", line 52, in split_and_send
    await message.answer(text)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "F:\OCR_telegram_bot\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "еп+1са+1оп" at byte offset 175
